### ISSUE TITLE
[BUG] Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.

### ISSUE THREAD

**Issue by Feriman22** [linuxserver/docker-ddclient#78] opened 2023-10-23 08:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It worked for a long time, but today (after a router restart), I'm getting this below error in logs:

`Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.`

### Expected Behavior

It should update the ddns IP.

### Steps To Reproduce

I have no idea how to reproduce.

### Environment

```markdown
- OS: Raspberry Pi OS Bookworm arm64
- How docker service was installed: Docker compose, via portainer
```

### CPU architecture

arm64

### Docker creation

```bash
version: "2.1"
services:
  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - /mnt/Docker/ddclient:/config
    restart: unless-stopped
    network_mode: bridge
```

### Container logs

```bash
Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.
Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.
Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.
Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.
Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.
Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.
Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.
Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.
Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.
Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.
Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.
Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.
Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.
Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.
Invalid version format (non-numeric data) at /usr/bin/ddclient line 24.
```

**Comment by Roxedus** [comment] 2023-10-23 08:17
Dupe of #77

**Closed by Roxedus** 2023-10-23 08:17 UTC
